
import java.sql.*;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Makoba Ngulube
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        ID_Number = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        Check = new javax.swing.JButton();
        Program = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Gender = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        View_All = new javax.swing.JButton();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Student Management System");

        jLabel2.setText("Student Name");

        jLabel3.setText("Student Number");

        ID_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_NumberActionPerformed(evt);
            }
        });

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        Check.setText("Check");
        Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckActionPerformed(evt);
            }
        });

        jLabel4.setText("Program");

        jLabel5.setText("Gender");

        View_All.setText("View_All");
        View_All.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_AllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Add)
                        .addGap(18, 18, 18)
                        .addComponent(Delete)
                        .addGap(18, 18, 18)
                        .addComponent(update)
                        .addGap(18, 18, 18)
                        .addComponent(Check)
                        .addGap(28, 28, 28)
                        .addComponent(View_All))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Gender)
                            .addComponent(ID_Number, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(Program)
                            .addComponent(Name))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Program, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add)
                    .addComponent(Delete)
                    .addComponent(update)
                    .addComponent(Check)
                    .addComponent(View_All))
                .addGap(93, 93, 93))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
                try {
            String url = "jdbc:derby://localhost:1527/students";
        String username = "root";
        String password = "10653";
        if(Name.getText() == "" || ID_Number.getText() == "" || Program.getText() == "" || Gender.getText() == ""){
            System.out.println("You cannot have empty fields");
        }
        else{
            Connection connect = DriverManager.getConnection(url, username, password);
            Statement stmt = connect.createStatement();
            String query = "insert into students (Name, ID, program, gender) values ('"+Name.getText()+"','"+ID_Number.getText()+"','"+Program.getText()+"','"+Gender.getText()+"')";
            stmt.execute(query);
            JOptionPane.showMessageDialog(rootPane, "Addition was successful");
            
        }  
        } 
        catch (SQLException ex) {
           JOptionPane.showMessageDialog(rootPane, "Addition Error........!");
        }
    }//GEN-LAST:event_AddActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
       try {
            String url = "jdbc:derby://localhost:1527/students";
        String username = "root";
        String password = "10653";
            Connection connect = DriverManager.getConnection(url, username, password);
            Statement stmt = connect.createStatement();
            String query = "DELETE FROM students WHERE ID = '"+ID_Number.getText()+"'";
            stmt.execute(query);
            JOptionPane.showMessageDialog(rootPane, "Deletion was successful");
            
            
        } 
        catch (SQLException ex) {
           JOptionPane.showMessageDialog(rootPane, "Delete Error.........!");
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try {
            String url = "jdbc:derby://localhost:1527/students";
        String username = "root";
        String password = "10653";
            Connection connect = DriverManager.getConnection(url, username, password);
            Statement stmt = connect.createStatement();
            String query = "update students set Name = '"+Name.getText()+"', program = '"+Program.getText()+"', gender = '"+Gender.getText()+"' where ID = '"+ID_Number.getText()+"'";
            stmt.execute(query);
            JOptionPane.showMessageDialog(rootPane, "Update successful");
            
            
        } 
        catch (SQLException ex) {
           JOptionPane.showMessageDialog(rootPane, "Update Error");
        }
    }//GEN-LAST:event_updateActionPerformed

    private void CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckActionPerformed
        try {
            String url = "jdbc:derby://localhost:1527/students";
        String username = "root";
        String password = "10653";
            Connection connect = DriverManager.getConnection(url, username, password);
            Statement stmt = connect.createStatement();
            String query = "select Name, ID, Program, Gender from students WHERE Name = '"+Name.getText()+"' and ID = '"+ID_Number.getText()+"' and Program = '"+Program.getText()+"' and gender = '"+Gender.getText()+"'";
            ResultSet rs = stmt.executeQuery(query);
            ResultSetMetaData rsmd = rs.getMetaData();
            int columnsNumber = rsmd.getColumnCount();
            

                while(rs.next()){
                for(int i = 1; i <= columnsNumber; i++){
                    System.out.println();
                    System.out.print(rs.getString(i));
                }
                System.out.println();
            }
            
            
        } 
        catch (SQLException ex) {
           JOptionPane.showMessageDialog(rootPane, "Check Error!!!");
        }
    }//GEN-LAST:event_CheckActionPerformed

    private void ID_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_NumberActionPerformed

    private void View_AllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_AllActionPerformed
         try {
            String url = "jdbc:derby://localhost:1527/students";
        String username = "root";
        String password = "10653";
            Connection connect = DriverManager.getConnection(url, username, password);
            Statement stmt = connect.createStatement();
            String query = "select * from students";
            ResultSet rs = stmt.executeQuery(query);
            ResultSetMetaData rsmd = rs.getMetaData();
            int columnsNumber = rsmd.getColumnCount();
            
            while(rs.next()){
                for(int i = 1; i <= columnsNumber; i++){
                    System.out.println();
                    System.out.print(rs.getString(i));
                }
                System.out.println();
            }
            
            
        } 
        catch (SQLException ex) {
        }
    }//GEN-LAST:event_View_AllActionPerformed

   
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Check;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField Gender;
    private javax.swing.JTextField ID_Number;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Program;
    private javax.swing.JButton View_All;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
